/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsRouteImport } from './routes/_ops'
import { Route as EdgeRouteImport } from './routes/edge'
import { Route as OpsModuleRouteImport } from './routes/_ops.$module'
import { Route as OpsAssetsRouteImport } from './routes/_ops.assets'
import { Route as OpsAuditRouteImport } from './routes/_ops.audit'
import { Route as OpsBiosecurityRouteImport } from './routes/_ops.biosecurity'
import { Route as OpsConflictsRouteImport } from './routes/_ops.conflicts'
import { Route as OpsContainersRouteImport } from './routes/_ops.containers'
import { Route as OpsDashboardRouteImport } from './routes/_ops.dashboard'
import { Route as OpsEnvironmentRouteImport } from './routes/_ops.environment'
import { Route as OpsInventoryRouteImport } from './routes/_ops.inventory'
import { Route as OpsManifestsRouteImport } from './routes/_ops.manifests'
import { Route as OpsMusterRouteImport } from './routes/_ops.muster'
import { Route as OpsNotificationsRouteImport } from './routes/_ops.notifications'
import { Route as OpsPermitsRouteImport } from './routes/_ops.permits'
import { Route as OpsSyncRouteImport } from './routes/_ops.sync'
import { Route as OpsTimelineRouteImport } from './routes/_ops.timeline'
import { Route as OpsWasteRouteImport } from './routes/_ops.waste'
import { Route as OpsCargoIndexRouteImport } from './routes/_ops.cargo.index'
import { Route as OpsCargoIdRouteImport } from './routes/_ops.cargo.$id'
import { Route as OpsExpeditionsIndexRouteImport } from './routes/_ops.expeditions.index'
import { Route as OpsIncidentsIndexRouteImport } from './routes/_ops.incidents.index'
import { Route as OpsIncidentsIdRouteImport } from './routes/_ops.incidents.$id'
import { Route as OpsPersonnelIndexRouteImport } from './routes/_ops.personnel.index'
import { Route as OpsPersonnelIdRouteImport } from './routes/_ops.personnel.$id'
import { Route as OpsSortiesIndexRouteImport } from './routes/_ops.sorties.index'
import { Route as OpsSortiesIdRouteImport } from './routes/_ops.sorties.$id'
import { Route as OpsExpeditionsIdIndexRouteImport } from './routes/_ops.expeditions.$id.index'
import { Route as OpsExpeditionsIdReadinessRouteImport } from './routes/_ops.expeditions.$id.readiness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/_ops',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeRoute = EdgeRouteImport.update({
  id: '/edge',
  path: '/edge',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsModuleRoute = OpsModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAssetsRoute = OpsAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAuditRoute = OpsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OpsRoute,
} as any)
const OpsBiosecurityRoute = OpsBiosecurityRouteImport.update({
  id: '/biosecurity',
  path: '/biosecurity',
  getParentRoute: () => OpsRoute,
} as any)
const OpsConflictsRoute = OpsConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => OpsRoute,
} as any)
const OpsContainersRoute = OpsContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDashboardRoute = OpsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OpsRoute,
} as any)
const OpsEnvironmentRoute = OpsEnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInventoryRoute = OpsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OpsRoute,
} as any)
const OpsManifestsRoute = OpsManifestsRouteImport.update({
  id: '/manifests',
  path: '/manifests',
  getParentRoute: () => OpsRoute,
} as any)
const OpsMusterRoute = OpsMusterRouteImport.update({
  id: '/muster',
  path: '/muster',
  getParentRoute: () => OpsRoute,
} as any)
const OpsNotificationsRoute = OpsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPermitsRoute = OpsPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSyncRoute = OpsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => OpsRoute,
} as any)
const OpsTimelineRoute = OpsTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => OpsRoute,
} as any)
const OpsWasteRoute = OpsWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => OpsRoute,
} as any)
const OpsCargoIndexRoute = OpsCargoIndexRouteImport.update({
  id: '/cargo/',
  path: '/cargo/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsCargoIdRoute = OpsCargoIdRouteImport.update({
  id: '/cargo/$id',
  path: '/cargo/$id',
  getParentRoute: () => OpsRoute,
} as any)
const OpsExpeditionsIndexRoute = OpsExpeditionsIndexRouteImport.update({
  id: '/expeditions/',
  path: '/expeditions/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsIncidentsIndexRoute = OpsIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsIncidentsIdRoute = OpsIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPersonnelIndexRoute = OpsPersonnelIndexRouteImport.update({
  id: '/personnel/',
  path: '/personnel/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPersonnelIdRoute = OpsPersonnelIdRouteImport.update({
  id: '/personnel/$id',
  path: '/personnel/$id',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSortiesIndexRoute = OpsSortiesIndexRouteImport.update({
  id: '/sorties/',
  path: '/sorties/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSortiesIdRoute = OpsSortiesIdRouteImport.update({
  id: '/sorties/$id',
  path: '/sorties/$id',
  getParentRoute: () => OpsRoute,
} as any)
const OpsExpeditionsIdIndexRoute = OpsExpeditionsIdIndexRouteImport.update({
  id: '/expeditions/$id/',
  path: '/expeditions/$id/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsExpeditionsIdReadinessRoute =
  OpsExpeditionsIdReadinessRouteImport.update({
    id: '/expeditions/$id/readiness',
    path: '/expeditions/$id/readiness',
    getParentRoute: () => OpsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edge': typeof EdgeRoute
  '/$module': typeof OpsModuleRoute
  '/assets': typeof OpsAssetsRoute
  '/audit': typeof OpsAuditRoute
  '/biosecurity': typeof OpsBiosecurityRoute
  '/conflicts': typeof OpsConflictsRoute
  '/containers': typeof OpsContainersRoute
  '/dashboard': typeof OpsDashboardRoute
  '/environment': typeof OpsEnvironmentRoute
  '/inventory': typeof OpsInventoryRoute
  '/manifests': typeof OpsManifestsRoute
  '/muster': typeof OpsMusterRoute
  '/notifications': typeof OpsNotificationsRoute
  '/permits': typeof OpsPermitsRoute
  '/sync': typeof OpsSyncRoute
  '/timeline': typeof OpsTimelineRoute
  '/waste': typeof OpsWasteRoute
  '/cargo/$id': typeof OpsCargoIdRoute
  '/incidents/$id': typeof OpsIncidentsIdRoute
  '/personnel/$id': typeof OpsPersonnelIdRoute
  '/sorties/$id': typeof OpsSortiesIdRoute
  '/cargo/': typeof OpsCargoIndexRoute
  '/expeditions/': typeof OpsExpeditionsIndexRoute
  '/incidents/': typeof OpsIncidentsIndexRoute
  '/personnel/': typeof OpsPersonnelIndexRoute
  '/sorties/': typeof OpsSortiesIndexRoute
  '/expeditions/$id/readiness': typeof OpsExpeditionsIdReadinessRoute
  '/expeditions/$id/': typeof OpsExpeditionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edge': typeof EdgeRoute
  '/$module': typeof OpsModuleRoute
  '/assets': typeof OpsAssetsRoute
  '/audit': typeof OpsAuditRoute
  '/biosecurity': typeof OpsBiosecurityRoute
  '/conflicts': typeof OpsConflictsRoute
  '/containers': typeof OpsContainersRoute
  '/dashboard': typeof OpsDashboardRoute
  '/environment': typeof OpsEnvironmentRoute
  '/inventory': typeof OpsInventoryRoute
  '/manifests': typeof OpsManifestsRoute
  '/muster': typeof OpsMusterRoute
  '/notifications': typeof OpsNotificationsRoute
  '/permits': typeof OpsPermitsRoute
  '/sync': typeof OpsSyncRoute
  '/timeline': typeof OpsTimelineRoute
  '/waste': typeof OpsWasteRoute
  '/cargo/$id': typeof OpsCargoIdRoute
  '/incidents/$id': typeof OpsIncidentsIdRoute
  '/personnel/$id': typeof OpsPersonnelIdRoute
  '/sorties/$id': typeof OpsSortiesIdRoute
  '/cargo': typeof OpsCargoIndexRoute
  '/expeditions': typeof OpsExpeditionsIndexRoute
  '/incidents': typeof OpsIncidentsIndexRoute
  '/personnel': typeof OpsPersonnelIndexRoute
  '/sorties': typeof OpsSortiesIndexRoute
  '/expeditions/$id/readiness': typeof OpsExpeditionsIdReadinessRoute
  '/expeditions/$id': typeof OpsExpeditionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_ops': typeof OpsRouteWithChildren
  '/edge': typeof EdgeRoute
  '/_ops/$module': typeof OpsModuleRoute
  '/_ops/assets': typeof OpsAssetsRoute
  '/_ops/audit': typeof OpsAuditRoute
  '/_ops/biosecurity': typeof OpsBiosecurityRoute
  '/_ops/conflicts': typeof OpsConflictsRoute
  '/_ops/containers': typeof OpsContainersRoute
  '/_ops/dashboard': typeof OpsDashboardRoute
  '/_ops/environment': typeof OpsEnvironmentRoute
  '/_ops/inventory': typeof OpsInventoryRoute
  '/_ops/manifests': typeof OpsManifestsRoute
  '/_ops/muster': typeof OpsMusterRoute
  '/_ops/notifications': typeof OpsNotificationsRoute
  '/_ops/permits': typeof OpsPermitsRoute
  '/_ops/sync': typeof OpsSyncRoute
  '/_ops/timeline': typeof OpsTimelineRoute
  '/_ops/waste': typeof OpsWasteRoute
  '/_ops/cargo/$id': typeof OpsCargoIdRoute
  '/_ops/incidents/$id': typeof OpsIncidentsIdRoute
  '/_ops/personnel/$id': typeof OpsPersonnelIdRoute
  '/_ops/sorties/$id': typeof OpsSortiesIdRoute
  '/_ops/cargo/': typeof OpsCargoIndexRoute
  '/_ops/expeditions/': typeof OpsExpeditionsIndexRoute
  '/_ops/incidents/': typeof OpsIncidentsIndexRoute
  '/_ops/personnel/': typeof OpsPersonnelIndexRoute
  '/_ops/sorties/': typeof OpsSortiesIndexRoute
  '/_ops/expeditions/$id/readiness': typeof OpsExpeditionsIdReadinessRoute
  '/_ops/expeditions/$id/': typeof OpsExpeditionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edge'
    | '/$module'
    | '/assets'
    | '/audit'
    | '/biosecurity'
    | '/conflicts'
    | '/containers'
    | '/dashboard'
    | '/environment'
    | '/inventory'
    | '/manifests'
    | '/muster'
    | '/notifications'
    | '/permits'
    | '/sync'
    | '/timeline'
    | '/waste'
    | '/cargo/$id'
    | '/incidents/$id'
    | '/personnel/$id'
    | '/sorties/$id'
    | '/cargo/'
    | '/expeditions/'
    | '/incidents/'
    | '/personnel/'
    | '/sorties/'
    | '/expeditions/$id/readiness'
    | '/expeditions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edge'
    | '/$module'
    | '/assets'
    | '/audit'
    | '/biosecurity'
    | '/conflicts'
    | '/containers'
    | '/dashboard'
    | '/environment'
    | '/inventory'
    | '/manifests'
    | '/muster'
    | '/notifications'
    | '/permits'
    | '/sync'
    | '/timeline'
    | '/waste'
    | '/cargo/$id'
    | '/incidents/$id'
    | '/personnel/$id'
    | '/sorties/$id'
    | '/cargo'
    | '/expeditions'
    | '/incidents'
    | '/personnel'
    | '/sorties'
    | '/expeditions/$id/readiness'
    | '/expeditions/$id'
  id:
    | '__root__'
    | '/'
    | '/_ops'
    | '/edge'
    | '/_ops/$module'
    | '/_ops/assets'
    | '/_ops/audit'
    | '/_ops/biosecurity'
    | '/_ops/conflicts'
    | '/_ops/containers'
    | '/_ops/dashboard'
    | '/_ops/environment'
    | '/_ops/inventory'
    | '/_ops/manifests'
    | '/_ops/muster'
    | '/_ops/notifications'
    | '/_ops/permits'
    | '/_ops/sync'
    | '/_ops/timeline'
    | '/_ops/waste'
    | '/_ops/cargo/$id'
    | '/_ops/incidents/$id'
    | '/_ops/personnel/$id'
    | '/_ops/sorties/$id'
    | '/_ops/cargo/'
    | '/_ops/expeditions/'
    | '/_ops/incidents/'
    | '/_ops/personnel/'
    | '/_ops/sorties/'
    | '/_ops/expeditions/$id/readiness'
    | '/_ops/expeditions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsRoute: typeof OpsRouteWithChildren
  EdgeRoute: typeof EdgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops': {
      id: '/_ops'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge': {
      id: '/edge'
      path: '/edge'
      fullPath: '/edge'
      preLoaderRoute: typeof EdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops/$module': {
      id: '/_ops/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof OpsModuleRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/assets': {
      id: '/_ops/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof OpsAssetsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/audit': {
      id: '/_ops/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof OpsAuditRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/biosecurity': {
      id: '/_ops/biosecurity'
      path: '/biosecurity'
      fullPath: '/biosecurity'
      preLoaderRoute: typeof OpsBiosecurityRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/conflicts': {
      id: '/_ops/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof OpsConflictsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/containers': {
      id: '/_ops/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof OpsContainersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/dashboard': {
      id: '/_ops/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof OpsDashboardRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/environment': {
      id: '/_ops/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof OpsEnvironmentRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/inventory': {
      id: '/_ops/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof OpsInventoryRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/manifests': {
      id: '/_ops/manifests'
      path: '/manifests'
      fullPath: '/manifests'
      preLoaderRoute: typeof OpsManifestsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/muster': {
      id: '/_ops/muster'
      path: '/muster'
      fullPath: '/muster'
      preLoaderRoute: typeof OpsMusterRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/notifications': {
      id: '/_ops/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof OpsNotificationsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/permits': {
      id: '/_ops/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof OpsPermitsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/sync': {
      id: '/_ops/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof OpsSyncRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/timeline': {
      id: '/_ops/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof OpsTimelineRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/waste': {
      id: '/_ops/waste'
      path: '/waste'
      fullPath: '/waste'
      preLoaderRoute: typeof OpsWasteRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/cargo/': {
      id: '/_ops/cargo/'
      path: '/cargo'
      fullPath: '/cargo/'
      preLoaderRoute: typeof OpsCargoIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/cargo/$id': {
      id: '/_ops/cargo/$id'
      path: '/cargo/$id'
      fullPath: '/cargo/$id'
      preLoaderRoute: typeof OpsCargoIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/expeditions/': {
      id: '/_ops/expeditions/'
      path: '/expeditions'
      fullPath: '/expeditions/'
      preLoaderRoute: typeof OpsExpeditionsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/incidents/': {
      id: '/_ops/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof OpsIncidentsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/incidents/$id': {
      id: '/_ops/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof OpsIncidentsIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/personnel/': {
      id: '/_ops/personnel/'
      path: '/personnel'
      fullPath: '/personnel/'
      preLoaderRoute: typeof OpsPersonnelIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/personnel/$id': {
      id: '/_ops/personnel/$id'
      path: '/personnel/$id'
      fullPath: '/personnel/$id'
      preLoaderRoute: typeof OpsPersonnelIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/sorties/': {
      id: '/_ops/sorties/'
      path: '/sorties'
      fullPath: '/sorties/'
      preLoaderRoute: typeof OpsSortiesIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/sorties/$id': {
      id: '/_ops/sorties/$id'
      path: '/sorties/$id'
      fullPath: '/sorties/$id'
      preLoaderRoute: typeof OpsSortiesIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/expeditions/$id/': {
      id: '/_ops/expeditions/$id/'
      path: '/expeditions/$id'
      fullPath: '/expeditions/$id/'
      preLoaderRoute: typeof OpsExpeditionsIdIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/expeditions/$id/readiness': {
      id: '/_ops/expeditions/$id/readiness'
      path: '/expeditions/$id/readiness'
      fullPath: '/expeditions/$id/readiness'
      preLoaderRoute: typeof OpsExpeditionsIdReadinessRouteImport
      parentRoute: typeof OpsRoute
    }
  }
}

interface OpsRouteChildren {
  OpsModuleRoute: typeof OpsModuleRoute
  OpsAssetsRoute: typeof OpsAssetsRoute
  OpsAuditRoute: typeof OpsAuditRoute
  OpsBiosecurityRoute: typeof OpsBiosecurityRoute
  OpsConflictsRoute: typeof OpsConflictsRoute
  OpsContainersRoute: typeof OpsContainersRoute
  OpsDashboardRoute: typeof OpsDashboardRoute
  OpsEnvironmentRoute: typeof OpsEnvironmentRoute
  OpsInventoryRoute: typeof OpsInventoryRoute
  OpsManifestsRoute: typeof OpsManifestsRoute
  OpsMusterRoute: typeof OpsMusterRoute
  OpsNotificationsRoute: typeof OpsNotificationsRoute
  OpsPermitsRoute: typeof OpsPermitsRoute
  OpsSyncRoute: typeof OpsSyncRoute
  OpsTimelineRoute: typeof OpsTimelineRoute
  OpsWasteRoute: typeof OpsWasteRoute
  OpsCargoIdRoute: typeof OpsCargoIdRoute
  OpsIncidentsIdRoute: typeof OpsIncidentsIdRoute
  OpsPersonnelIdRoute: typeof OpsPersonnelIdRoute
  OpsSortiesIdRoute: typeof OpsSortiesIdRoute
  OpsCargoIndexRoute: typeof OpsCargoIndexRoute
  OpsExpeditionsIndexRoute: typeof OpsExpeditionsIndexRoute
  OpsIncidentsIndexRoute: typeof OpsIncidentsIndexRoute
  OpsPersonnelIndexRoute: typeof OpsPersonnelIndexRoute
  OpsSortiesIndexRoute: typeof OpsSortiesIndexRoute
  OpsExpeditionsIdReadinessRoute: typeof OpsExpeditionsIdReadinessRoute
  OpsExpeditionsIdIndexRoute: typeof OpsExpeditionsIdIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsModuleRoute: OpsModuleRoute,
  OpsAssetsRoute: OpsAssetsRoute,
  OpsAuditRoute: OpsAuditRoute,
  OpsBiosecurityRoute: OpsBiosecurityRoute,
  OpsConflictsRoute: OpsConflictsRoute,
  OpsContainersRoute: OpsContainersRoute,
  OpsDashboardRoute: OpsDashboardRoute,
  OpsEnvironmentRoute: OpsEnvironmentRoute,
  OpsInventoryRoute: OpsInventoryRoute,
  OpsManifestsRoute: OpsManifestsRoute,
  OpsMusterRoute: OpsMusterRoute,
  OpsNotificationsRoute: OpsNotificationsRoute,
  OpsPermitsRoute: OpsPermitsRoute,
  OpsSyncRoute: OpsSyncRoute,
  OpsTimelineRoute: OpsTimelineRoute,
  OpsWasteRoute: OpsWasteRoute,
  OpsCargoIdRoute: OpsCargoIdRoute,
  OpsIncidentsIdRoute: OpsIncidentsIdRoute,
  OpsPersonnelIdRoute: OpsPersonnelIdRoute,
  OpsSortiesIdRoute: OpsSortiesIdRoute,
  OpsCargoIndexRoute: OpsCargoIndexRoute,
  OpsExpeditionsIndexRoute: OpsExpeditionsIndexRoute,
  OpsIncidentsIndexRoute: OpsIncidentsIndexRoute,
  OpsPersonnelIndexRoute: OpsPersonnelIndexRoute,
  OpsSortiesIndexRoute: OpsSortiesIndexRoute,
  OpsExpeditionsIdReadinessRoute: OpsExpeditionsIdReadinessRoute,
  OpsExpeditionsIdIndexRoute: OpsExpeditionsIdIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsRoute: OpsRouteWithChildren,
  EdgeRoute: EdgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
